### ISSUE TITLE
fix inconsistency in list response

### ISSUE THREAD

**Issue by balmas** [alpheios-project/user-word-api#3]
Per @irina060981 It returns an array of words, but some array items have a "body" property and some of them don't.

**Comment by balmas** [comment]
@irina060981 is there a chance this could have been introduced on the client side? I verified that all the api code does is store and return the JSON as it was provided. I think we DO need to add data validation there before storing the data, and can add that, but can you check the client side code? I note that the two items returned inside a body property are from just about the same time -- maybe it's a difference between the application code and the test code?

**Comment by irina060981** [comment]
Right, it was my fault. I have sent data in different format with body property and without.
I expected that data is taken from body property on the server-side.
But as it is taken directly - I will fix the api requests.
So there is no bug here - I think it could be closed!

**Comment by balmas** [comment]
ok, will close this, but will open another to add data validation :-)
