### ISSUE TITLE
add data validation

### ISSUE THREAD

**Issue by balmas** [alpheios-project/user-word-api#4]
we should add some validation to make sure we don't store invalid data

**Comment by balmas** [comment]
@monzug to test this, you need to pull the webextension build from the the worddev branch of the webextension repo https://github.com/alpheios-project/webextension/tree/worddev/dist
That's qa-3.0.1.77 but the environment file (env-webext.js) has been changed to point at a dev instance of the user-word-api at https://userapis-dev.alpheios.net.  

The instance of the user-word-api that is deployed there has data validation added to the create and update operations, to try to prevent misuse of our API endpoints.

It requires a regression of the user word list functionality, to make sure creating and updating  of user word list items still work as expected.

**Comment by monzug** [comment]
so I need to test the functionality of wordlist, correct?

**Comment by balmas** [comment]
Yes, specifically focusing on adding new words and updating existing words (and confirming that those changes are saved correctly and available upon next login)
